server:
  port: 8082

logging:
  level:
    org.springframework.web: INFO
    ROOT: INFO
    com.onixnet.broadcom: INFO
  file: logs/app.log


spring:
  application:
    name: BeanApp

  h2:
    console:
      enabled: true
      settings.web-allow-others: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/formapp
    name:
    username: sa
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: "create-drop"
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

  mvc:
    favicon:
      enabled: false


  data:
    rest:
      basePath: "/api/v1"

application:
